name = input("Hello, welcome to Oundle Dating Sim (ODS). What would you like your Username to be?")
age = input("What is you age?")
if age >= 18:
        print("You are eligable to date. Here are your matches:")
print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg",)
print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg",)
print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg",)
print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg",)
print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg",)
print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg",)
print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg",)
print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg",)
print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
person_1 = print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
person_2 = print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
person_3 = print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
person_4 = print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
person_5 = print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
person_6 = print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
person_7 = print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
person_8 = print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
person_9 = print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
person_10 = print("Name: Gwedolen", "Age: 18", "Height: 158cm", "Weight: 45kg")
